CREATE TABLE `meeting_tags` (
	`id` int AUTO_INCREMENT NOT NULL,
	`meetingId` int NOT NULL,
	`tagId` int NOT NULL,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `meeting_tags_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `meetings` (
	`id` int AUTO_INCREMENT NOT NULL,
	`meetingDate` timestamp NOT NULL,
	`primaryLead` varchar(255) NOT NULL,
	`participants` text NOT NULL,
	`organizations` text,
	`jurisdictions` text,
	`executiveSummary` text NOT NULL,
	`strategicHighlights` text,
	`opportunities` text,
	`risks` text,
	`keyQuotes` text,
	`intelligenceData` text,
	`fullTranscript` text,
	`sourceType` enum('plaud','fathom','manual') NOT NULL,
	`sourceId` varchar(255),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	`createdBy` int,
	CONSTRAINT `meetings_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `tags` (
	`id` int AUTO_INCREMENT NOT NULL,
	`name` varchar(255) NOT NULL,
	`type` enum('sector','jurisdiction') NOT NULL,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `tags_id` PRIMARY KEY(`id`),
	CONSTRAINT `tags_name_unique` UNIQUE(`name`)
);
--> statement-breakpoint
CREATE TABLE `tasks` (
	`id` int AUTO_INCREMENT NOT NULL,
	`title` varchar(500) NOT NULL,
	`description` text,
	`priority` enum('low','medium','high') NOT NULL DEFAULT 'medium',
	`status` enum('open','in_progress','completed') NOT NULL DEFAULT 'open',
	`assignedTo` int,
	`meetingId` int,
	`isAutoGenerated` boolean NOT NULL DEFAULT false,
	`dueDate` timestamp,
	`completedAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	`createdBy` int,
	CONSTRAINT `tasks_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
ALTER TABLE `meeting_tags` ADD CONSTRAINT `meeting_tags_meetingId_meetings_id_fk` FOREIGN KEY (`meetingId`) REFERENCES `meetings`(`id`) ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `meeting_tags` ADD CONSTRAINT `meeting_tags_tagId_tags_id_fk` FOREIGN KEY (`tagId`) REFERENCES `tags`(`id`) ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `meetings` ADD CONSTRAINT `meetings_createdBy_users_id_fk` FOREIGN KEY (`createdBy`) REFERENCES `users`(`id`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `tasks` ADD CONSTRAINT `tasks_assignedTo_users_id_fk` FOREIGN KEY (`assignedTo`) REFERENCES `users`(`id`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `tasks` ADD CONSTRAINT `tasks_meetingId_meetings_id_fk` FOREIGN KEY (`meetingId`) REFERENCES `meetings`(`id`) ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `tasks` ADD CONSTRAINT `tasks_createdBy_users_id_fk` FOREIGN KEY (`createdBy`) REFERENCES `users`(`id`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX `meeting_id_idx` ON `meeting_tags` (`meetingId`);--> statement-breakpoint
CREATE INDEX `tag_id_idx` ON `meeting_tags` (`tagId`);--> statement-breakpoint
CREATE INDEX `meeting_date_idx` ON `meetings` (`meetingDate`);--> statement-breakpoint
CREATE INDEX `primary_lead_idx` ON `meetings` (`primaryLead`);--> statement-breakpoint
CREATE INDEX `source_id_idx` ON `meetings` (`sourceId`);--> statement-breakpoint
CREATE INDEX `type_idx` ON `tags` (`type`);--> statement-breakpoint
CREATE INDEX `status_idx` ON `tasks` (`status`);--> statement-breakpoint
CREATE INDEX `assigned_to_idx` ON `tasks` (`assignedTo`);--> statement-breakpoint
CREATE INDEX `meeting_id_idx` ON `tasks` (`meetingId`);