import { useState } from "react";
import { trpc } from "@/lib/trpc";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Checkbox } from "@/components/ui/checkbox";
import { Link } from "wouter";
import { 
  CheckSquare, 
  Square,
  Clock,
  User,
  FileText,
  Loader2,
  AlertCircle,
  CheckCircle2,
  Circle
} from "lucide-react";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { toast } from "sonner";

export default function ToDo() {
  const [statusFilter, setStatusFilter] = useState<string>("all");
  const [priorityFilter, setPriorityFilter] = useState<string>("all");

  const { data: tasks, isLoading, refetch } = trpc.tasks.list.useQuery({
    status: statusFilter !== "all" ? (statusFilter as "open" | "in_progress" | "completed") : undefined,
  });

  const updateTaskMutation = trpc.tasks.update.useMutation({
    onSuccess: () => {
      refetch();
      toast.success("Task updated");
    },
    onError: () => {
      toast.error("Failed to update task");
    },
  });

  const handleToggleStatus = async (taskId: number, currentStatus: string) => {
    let newStatus: "open" | "in_progress" | "completed";
    
    if (currentStatus === "completed") {
      newStatus = "open";
    } else if (currentStatus === "open") {
      newStatus = "in_progress";
    } else {
      newStatus = "completed";
    }

    await updateTaskMutation.mutateAsync({
      id: taskId,
      status: newStatus,
    });
  };

  // Filter by priority on client side
  const filteredTasks = tasks?.filter((task) => {
    if (priorityFilter !== "all" && task.priority !== priorityFilter) {
      return false;
    }
    return true;
  }) || [];

  // Group tasks by status
  const openTasks = filteredTasks.filter((t) => t.status === "open");
  const inProgressTasks = filteredTasks.filter((t) => t.status === "in_progress");
  const completedTasks = filteredTasks.filter((t) => t.status === "completed");

  const getPriorityColor = (priority: string) => {
    switch (priority) {
      case "high":
        return "text-red-500 border-red-500/20 bg-red-500/10";
      case "medium":
        return "text-yellow-500 border-yellow-500/20 bg-yellow-500/10";
      case "low":
        return "text-blue-500 border-blue-500/20 bg-blue-500/10";
      default:
        return "text-zinc-500 border-zinc-500/20 bg-zinc-500/10";
    }
  };

  const getStatusIcon = (status: string) => {
    switch (status) {
      case "completed":
        return <CheckCircle2 className="h-5 w-5 text-green-500" />;
      case "in_progress":
        return <Clock className="h-5 w-5 text-yellow-500" />;
      default:
        return <Circle className="h-5 w-5 text-zinc-500" />;
    }
  };

  const TaskCard = ({ task }: { task: NonNullable<typeof tasks>[0] }) => (
    <Card className="bg-zinc-900 border-zinc-800 p-4 hover:border-yellow-600/50 transition-all group">
      <div className="flex items-start gap-4">
        {/* Status Checkbox */}
        <button
          onClick={() => handleToggleStatus(task.id, task.status)}
          className="mt-1 flex-shrink-0"
          disabled={updateTaskMutation.isPending}
        >
          {getStatusIcon(task.status)}
        </button>

        {/* Task Content */}
        <div className="flex-1 min-w-0">
          <div className="flex items-start justify-between gap-4 mb-2">
            <h3 className={`font-medium ${task.status === "completed" ? "text-zinc-500 line-through" : "text-white"}`}>
              {task.title}
            </h3>
            <Badge className={getPriorityColor(task.priority)}>
              {task.priority}
            </Badge>
          </div>

          {task.description && (
            <p className="text-sm text-zinc-400 mb-3 line-clamp-2">
              {task.description}
            </p>
          )}

          {/* Metadata */}
          <div className="flex flex-wrap gap-4 text-xs text-zinc-500">
            {task.dueDate && (
              <div className="flex items-center gap-1">
                <Clock className="h-3 w-3" />
                <span>
                  Due {new Date(task.dueDate).toLocaleDateString("en-US", {
                    month: "short",
                    day: "numeric",
                  })}
                </span>
              </div>
            )}
            
            {task.meetingId && (
              <Link href={`/meeting/${task.meetingId}`}>
                <div className="flex items-center gap-1 hover:text-yellow-600 cursor-pointer">
                  <FileText className="h-3 w-3" />
                  <span>From meeting</span>
                </div>
              </Link>
            )}

            {task.isAutoGenerated && (
              <Badge variant="outline" className="border-zinc-700 text-zinc-500 text-xs">
                Auto-generated
              </Badge>
            )}
          </div>
        </div>
      </div>
    </Card>
  );

  return (
    <div className="min-h-screen bg-black">
      <div className="container max-w-7xl py-8">
        {/* Header */}
        <div className="mb-8">
          <h1 className="text-3xl font-bold text-white mb-2">To-Do</h1>
          <p className="text-zinc-400">Track action items from meetings and manage tasks</p>
        </div>

        {/* Filters */}
        <Card className="bg-zinc-900 border-zinc-800 p-6 mb-6">
          <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
            {/* Status Filter */}
            <Select value={statusFilter} onValueChange={setStatusFilter}>
              <SelectTrigger className="bg-zinc-800 border-zinc-700 text-white">
                <CheckSquare className="h-4 w-4 mr-2 text-zinc-400" />
                <SelectValue placeholder="All Statuses" />
              </SelectTrigger>
              <SelectContent className="bg-zinc-800 border-zinc-700">
                <SelectItem value="all">All Statuses</SelectItem>
                <SelectItem value="open">Open</SelectItem>
                <SelectItem value="in_progress">In Progress</SelectItem>
                <SelectItem value="completed">Completed</SelectItem>
              </SelectContent>
            </Select>

            {/* Priority Filter */}
            <Select value={priorityFilter} onValueChange={setPriorityFilter}>
              <SelectTrigger className="bg-zinc-800 border-zinc-700 text-white">
                <AlertCircle className="h-4 w-4 mr-2 text-zinc-400" />
                <SelectValue placeholder="All Priorities" />
              </SelectTrigger>
              <SelectContent className="bg-zinc-800 border-zinc-700">
                <SelectItem value="all">All Priorities</SelectItem>
                <SelectItem value="high">High Priority</SelectItem>
                <SelectItem value="medium">Medium Priority</SelectItem>
                <SelectItem value="low">Low Priority</SelectItem>
              </SelectContent>
            </Select>

            {/* Stats */}
            <div className="flex items-center justify-end gap-6 text-sm">
              <div className="text-zinc-400">
                <span className="font-medium text-white">{openTasks.length}</span> open
              </div>
              <div className="text-zinc-400">
                <span className="font-medium text-yellow-600">{inProgressTasks.length}</span> in progress
              </div>
              <div className="text-zinc-400">
                <span className="font-medium text-green-600">{completedTasks.length}</span> done
              </div>
            </div>
          </div>
        </Card>

        {/* Tasks List */}
        {isLoading ? (
          <div className="flex items-center justify-center py-12">
            <Loader2 className="h-8 w-8 animate-spin text-yellow-600" />
          </div>
        ) : filteredTasks.length === 0 ? (
          <Card className="bg-zinc-900 border-zinc-800 p-12 text-center">
            <CheckSquare className="h-12 w-12 text-zinc-600 mx-auto mb-4" />
            <h3 className="text-lg font-medium text-white mb-2">No tasks found</h3>
            <p className="text-zinc-400">
              {statusFilter !== "all" || priorityFilter !== "all"
                ? "Try adjusting your filters"
                : "Tasks will appear here when meetings are processed"}
            </p>
          </Card>
        ) : (
          <div className="space-y-6">
            {/* Open Tasks */}
            {openTasks.length > 0 && (
              <div>
                <h2 className="text-lg font-semibold text-white mb-4 flex items-center gap-2">
                  <Circle className="h-5 w-5 text-zinc-500" />
                  Open ({openTasks.length})
                </h2>
                <div className="space-y-3">
                  {openTasks.map((task) => (
                    <TaskCard key={task.id} task={task} />
                  ))}
                </div>
              </div>
            )}

            {/* In Progress Tasks */}
            {inProgressTasks.length > 0 && (
              <div>
                <h2 className="text-lg font-semibold text-white mb-4 flex items-center gap-2">
                  <Clock className="h-5 w-5 text-yellow-500" />
                  In Progress ({inProgressTasks.length})
                </h2>
                <div className="space-y-3">
                  {inProgressTasks.map((task) => (
                    <TaskCard key={task.id} task={task} />
                  ))}
                </div>
              </div>
            )}

            {/* Completed Tasks */}
            {completedTasks.length > 0 && (
              <div>
                <h2 className="text-lg font-semibold text-white mb-4 flex items-center gap-2">
                  <CheckCircle2 className="h-5 w-5 text-green-500" />
                  Completed ({completedTasks.length})
                </h2>
                <div className="space-y-3">
                  {completedTasks.map((task) => (
                    <TaskCard key={task.id} task={task} />
                  ))}
                </div>
              </div>
            )}
          </div>
        )}
      </div>
    </div>
  );
}
